### ISSUE TITLE
parse returns false always

### ISSUE THREAD

**Issue by assemmarwan** [bushev/nodejs-license-file#2]
The function parse returns false always. I think it has to do with readFileSync where you need to supply the encoding "utf8".

**Comment by bushev** [comment]
Hi!

Please, try v1.1.1

**Comment by assemmarwan** [comment]
Hello,
I have updated to v1.1.1, but the problem still persists. Is it because of the public/private key that I generated using openssl? What tool to use to generate the keys? And what specifications?

**Comment by bushev** [comment]
Hello!

I use OpenSSL to get a keypair. I updated [docs](https://github.com/bushev/nodejs-license-file#generate-a-keypair-using-openssl) with keypair generation commands. Let me know if it helps.

**Comment by assemmarwan** [comment]
Thank you.

I have found the problem. My data object contains a property that is a number when generating. When parsing, it's returned as a string which made the data seem like they are different, hence always false.

 I suggest that you specify that the object should contain properties of type 'string' only or converting the data type within the lib to string.

**Comment by bushev** [comment]
Yes, thank you!

Please, try 1.1.3
