### ISSUE TITLE
parse should have a variant where the public key is passed by value and not by a file

### ISSUE THREAD

**Issue by Ognian** [bushev/nodejs-license-file#3]
Hi,
shouldn't there be a variant of the parse function where the public key data is passed as a string instead of an external file? This should help to use this in real world where otherwise everyone could generate their license and key pair :-)
What do you think?
Thanks
Ognian

**Comment by bushev** [comment]
Hi Ognian,

this is a good idea. I can extend `generate` and `parse` functions.

**Comment by bushev** [comment]
Hi, please check it out https://github.com/bushev/nodejs-license-file/commit/08cc78b41dee01a2b09a4809a013b73a52f9825c

**Comment by bushev** [comment]
BTW, I just release 2.0.0 with breaking improvement of parsing procedure. Now `parse` function works with `template` instead for `parseFunction`.

**Comment by Ognian** [comment]
Hi,
good work and it works, although I still have some ideas for improvement:
- you should embed the default template as a string, and not read it from a file; This would also enable webpack to correctly embed this lib into the source ...
- remove from the standard template the "== BEGIN LICENSE ==" and "== END LICENSE ==" lines it marks the resulting code to clearly ...

And the hardest one for which i have no good solution at the moment:
- what should prevent someone to easily hack the resulting code (even uglyfied) to circumvent this lib?

What do you think?
Thanks a lot
Ognian

**Comment by bushev** [comment]
Hi,
- +1 for "embed the default template";
- I'm not sure about it;
- Considering that the check takes place on the client, I do not think that it can be safe in principle (so all the clients can be cracked today);

**Comment by Ognian** [comment]
Hmm,
I searched a little bit around, and looked at my uglified code:
- maybe it would be best to totally remove the standard template, since now it is very easy to add one, and with these begin and end lines and the fact that strings are preserved you must be blind not to find the place in uglified code where licensing happens ;-)

**Comment by bushev** [comment]
Hello!

Yes, I get it. And yes, it looks like a good idea. I will remove default template.

**Comment by Ognian** [comment]
Will you be able to change this soon?

**Comment by bushev** [comment]
Hi!

I'm sorry, I'm overloaded before a Christmas time with a customer's projects... Hope I will be able to change the module after that.

**Comment by Ognian** [comment]
Thanks, no problem...

**Comment by bushev** [comment]
Hi!

Just created the PR: https://github.com/bushev/nodejs-license-file/pull/4 Could you please check is out?

**Comment by Ognian** [comment]
Yes, it works.
Thanks a lot

**Comment by bushev** [comment]
Tagged
