### ISSUE TITLE
JSON Stringify key order

### ISSUE THREAD

**Issue by muralikg** [bushev/nodejs-license-file#5]
```js
data = JSON.stringify(LicenseFile._prepareDataObject(options.data));
```
I noticed that you are using JSON serialization for signing data. The order of keys in the serialized string is not guaranteed. You might want to specify an explicit order, something which remains same during generation and verification, alphabetically ordering the keys should work too.

This [SO](https://stackoverflow.com/questions/16167581/sort-object-properties-and-json-stringify) post might help

**Comment by bushev** [comment]
Hi Murali!

Yes, it looks reasonable!

**Comment by bushev** [comment]
Please, check out new tag - 4.0.0

**Comment by muralikg** [comment]
Looks good @bushev 
Thanks for the library. Has been very helpful
